# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2018 BayLibre, SAS
#
# Author: Neil Armstrong <narmstrong@baylibre.com>

obj-$(CONFIG_VIDEO_MESON) = meson_vpu.o meson_vpu_init.o meson_canvas.o
obj-$(CONFIG_VIDEO_MESON) += meson_plane.o meson_venc.o meson_vclk.o
obj-$(CONFIG_VIDEO_MESON) += simplefb_common.o
obj-$(CONFIG_VIDEO_MESON_DW_HDMI) += meson_dw_hdmi.o ../dw_hdmi.o
obj-$(CONFIG_VIDEO_MESON_DW_MIPI_DSI) += meson_dw_mipi_dsi.o
